version: "3.9"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: jobbot_n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
    env_file:
      - .env
    restart: unless-stopped

  jobbot:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    container_name: jobbot_playwright
    command: sleep infinity
    ports:
      - "3000:3000"
    volumes:
      - ./data/:/app/data
      - ./src/:/app/src
    env_file:
      - .env
    restart: unless-stopped

volumes:
  n8n_data: {}
